### ISSUE TITLE
[Bug] Stopped working

### ISSUE THREAD

**Issue by Dmon1cDragon** [avi12/twitch-cp-bonus-collector#10]
### Describe the bug

The bonus collector isn't collecting on Microsoft Edge

### How to reproduce

Go on to a streamers page on twitch and wait until the collector box pops up

### Expected behavior

It should be auto collecting channel points on twitch

### What browser(s) can you reproduce the issue on?

Chromium Edge

### What OS does it occur on?

Windows

### What's the version you're running?

2.0.16

**Comment by avi12** [comment]
Fixed in #9
Wait until the store approves it and occasionally try to force update on your browser

**Comment by eiqnepm** [comment]
Does Firefox usually take a while to update their extensions? I can see the version is still 2.0.16. When I try to install it manually using the releases I'm told I can't because it's unverified

**Comment by avi12** [comment]
Huh, it seems like my [updater tool](https://github.com/avi12/web-ext-deploy) didn't quite work, good catch

**Comment by avi12** [comment]
I pushed update 2.1.0 to the Firefox store, hopefully it'll be approved ASAP

**Comment by eiqnepm** [comment]
Just manually checked for an update and it worked, thanks!
