### ISSUE TITLE
Exclude non-stream pages

### ISSUE THREAD

**Issue by Californ1a** [avi12/twitch-cp-bonus-collector#2]
With the extension enabled, when you open twitch.tv/friends, it automatically clicks on remove for them all, essentially clearing your friends list. Similarly, on twitch.tv/friends/requests, it won't allow you to click on accept if you have a friend request.

**Comment by avi12** [comment]
Sorry for the late response. I only recently enabled email notifications
As for the issue, I didn't know about this page, so that's a good point
I will work on a bug fix update soon
