### ISSUE TITLE
[Bug] Not claiming bonus points

### ISSUE THREAD

**Issue by jacadiaUNRULY** [avi12/twitch-cp-bonus-collector#8]
### Describe the bug

Within the last couple of hours the extension will not claim my bonus points. Haven't had an issue up until now. 

### How to reproduce

N/A

### Expected behavior

The bonus points should be claimed

### What browser(s) can you reproduce the issue on?

Opera

### What OS does it occur on?

Windows

### What's the version you're running?

2.0.16

**Comment by jnrz81** [comment]
I'm experiencing the same issue. I'm using Microsoft Edge with the latest update.

**Comment by avi12** [comment]
Pushed update [2.1.0](../releases/tag/2.1.0)
